# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run the gemspec command
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{date_scopes}
  s.version = "0.1.1"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Victor Sokolov"]
  s.date = %q{2010-12-09}
  s.description = %q{MySQL date functions for AREL 2 + AR 3 date scopes}
  s.email = %q{gzigzigzeo@gmail.com}
  s.extra_rdoc_files = [
    "README.rdoc"
  ]
  s.files = [
    "README.rdoc",
     "Rakefile",
     "lib/date_scopes.rb",
     "lib/date_scopes/active_record.rb",
     "lib/date_scopes/arel.rb",
     "lib/date_scopes/railtie.rb",
     "spec/date_scopes/date_scopes_arel_spec.rb",
     "spec/date_scopes/date_scopes_spec.rb",
     "spec/spec_helper.rb",
     "spec/support/fake_record.rb"
  ]
  s.homepage = %q{http://github.com/gzigzigzeo/date-scopes}
  s.rdoc_options = ["--charset=UTF-8"]
  s.require_paths = ["lib"]
  s.rubygems_version = %q{1.3.7}
  s.summary = %q{MySQL date functions for AREL 2 + AR 3 date scopes}
  s.test_files = [
    "spec/date_scopes/date_scopes_arel_spec.rb",
     "spec/date_scopes/date_scopes_spec.rb",
     "spec/spec_helper.rb",
     "spec/support/fake_record.rb"
  ]

  if s.respond_to? :specification_version then
    current_version = Gem::Specification::CURRENT_SPECIFICATION_VERSION
    s.specification_version = 3

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
    else
    end
  else
  end
end

